logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://hydrangea:hydrangea@localhost:27017/hydrangea?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: hydrangea
  datasource:
    url: jdbc:postgresql://localhost:5432/hydrangea
    username: hydrangea
    password: hydrangea
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show_sql: true

cors:
  allowed-origins:
    - http://localhost:5173

token:
  access-token:
    name: accessToken
    expiration-seconds: 86400
